namespace NQueen.Kernel.Solvers;

/// <summary>
/// Heuristics for selecting optimal parallel root split depth and determining whether to use parallelism.
/// Estimation avoids floating-point and uses saturated integer permutation math to approximate root fan-out.
/// </summary>
internal static class ParallelSplitDepthHeuristic
{
    /// <summary>
    /// Returns a split depth optimized for the given board size and logical core count.
    /// Behavior is preserved for N <= 13 (1/2), dynamic for N >= 14 using permutation-based fan-out estimate.
    /// </summary>
    public static int GetOptimalSplitDepth(int boardSize, int? logicalCoreCount = null)
    {
        // Preserve existing behavior for small/medium boards
        if (boardSize <= 10)
            return 1;
        if (boardSize <= 13)
            return 2;

        // For larger boards, estimate the number of root tasks generated by splitting d columns.
        // Prefer d=3 unless it greatly overproduces tasks; fall back to d=2 in that case.
        int cores = GetCoreCount(logicalCoreCount);
        int maxDepth = 3; // keep the same cap the codebase expects
        int d = Math.Min(maxDepth, boardSize);

        // Task budget windows: slightly wider for larger boards to keep workers busy.
        // min ~ 4x cores keeps all logical CPUs fed; max clamps runaway explosion.
        int minTasks = cores * (boardSize >= 18 ? 8 : 4);
        int maxTasks = cores * 256;

        int est3 = EstimatePermutationCountSaturated(boardSize, Math.Min(3, boardSize));
        if (est3 >= minTasks && est3 <= maxTasks)
            return 3;
        if (est3 > maxTasks)
            return 2;

        // If d=3 too small for some reason (unlikely), prefer the deeper split; otherwise fallback to 2.
        // Evaluate d=2 as a baseline.
        int est2 = EstimatePermutationCountSaturated(boardSize, Math.Min(2, boardSize));
        if (est2 >= minTasks && est2 <= maxTasks)
            return 2;

        // In practice we do not return 1 for N >= 14 to preserve prior behavior,
        // but keep a defensive fallback if estimates are anomalous.
        return 2;
    }

    /// <summary>
    /// Returns true if parallel mode should be used for "All" solutions.
    /// Keeps prior threshold while also requiring at least 2 logical cores.
    /// </summary>
    public static bool ShouldUseParallelForAll(int boardSize, int? logicalCoreCount = null) =>
        boardSize >= 12 && GetCoreCount(logicalCoreCount) > 1;

    /// <summary>
    /// Convenience API that provides split depth, target root budget, and parallel decision in one call.
    /// Callers can use TargetRoots to pre-size work queues if needed.
    /// </summary>
    public static SplitPlan GetSplitPlan(int boardSize, int? logicalCoreCount = null)
    {
        int cores = GetCoreCount(logicalCoreCount);
        int splitDepth = GetOptimalSplitDepth(boardSize, cores);
        // Use the same budget rules as GetOptimalSplitDepth for consistency
        int targetRoots = cores * (boardSize >= 18 ? 8 : 4);
        bool useParallel = ShouldUseParallelForAll(boardSize, cores);
        return new SplitPlan(splitDepth, Math.Max(cores, targetRoots), useParallel);
    }

    /// <summary>
    /// Estimates N P d (permutations without repetition) with saturation at int.MaxValue to avoid overflow.
    /// For example, N=14, d=3 => 14*13*12.
    /// </summary>
    private static int EstimatePermutationCountSaturated(int n, int depth)
    {
        if (n <= 0 || depth <= 0) return 0;
        long acc = 1;
        for (int i = 0; i < depth; i++)
        {
            acc *= (n - i);
            if (acc >= int.MaxValue) return int.MaxValue;
        }
        return (int)acc;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static int GetCoreCount(int? logicalCoreCount) =>
        logicalCoreCount.HasValue && logicalCoreCount.Value > 0
            ? logicalCoreCount.Value
            : Environment.ProcessorCount;

    public readonly record struct SplitPlan(int SplitDepth, int TargetRoots, bool UseParallel);
}
