global using NQueen.Domain.Enums;
global using NQueen.Domain.EventArgs;
global using NQueen.Domain.Interfaces;
global using NQueen.Domain.Models;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Text;
