global using NQueen.Domain.Enums;
global using NQueen.Domain.EventArgs;
global using NQueen.Domain.Interfaces;
global using NQueen.Domain.Models;
global using NQueen.Domain.Settings;
global using System.Collections;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Text;
