namespace NQueen.GUI.ViewModels;

public sealed partial class MainViewModel
{
    private void Cancel()
    {
        if (IsSimulating == false)
            return;

        // Flag cancellation so event handlers short‑circuit.
        _solver.IsSolverCanceled = true;
        _currentSimulationToken = Guid.Empty;

        try
        {
            CancellationTokenSource?.Cancel();
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[Cancel] CancellationTokenSource.Cancel threw: {ex}");
        }

        // Detach events first to avoid any further additions to ObservableSolutions.
        UnsubscribeFromSimulationEvents();

        // Perform all UI-bound collection / property changes on the UI dispatcher to avoid race / stale visuals.
        _uiDispatcher.Invoke(() =>
        {
            // Clear visualization & list (ensure SelectedSolution cleared before repopulating anywhere).
            SelectedSolution = null!;
            ObservableSolutions.Clear();
            ChessboardVm?.ClearImages();

            NoOfSolutions = "0";
            ElapsedTimeInSec = $"{0,0:N1}";
            MemoryUsage = "0";
            IsOutputReady = false;

            ProgressValue = 0;
            ProgressLabel = string.Empty;
            ProgressVisibility = Visibility.Hidden;
            ProgressLabelVisibility = Visibility.Hidden;

            // Reset primary state flags
            IsSimulating = false;
            IsSingleRunning = false;
            IsInInputMode = true;
            IsIdle = true;
        });

        // Fresh CTS for next run
        try { CancellationTokenSource?.Dispose(); } catch { /* ignore */ }
        CancellationTokenSource = new CancellationTokenSource();

        RefreshCommandStates();
    }

    private void Save()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return;

        var filePath = _saveFileService.ShowSaveFileDialog();
        if (string.IsNullOrEmpty(filePath))
            return;

        try
        {
            var content = GenerateSaveContent();
            _saveFileService.SaveContent(filePath, content);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[Save] Error during save operation: {ex.Message}");
            throw;
        }
    }

    private bool CanSimulate() => IsValid && HasErrors == false;

    private bool CanCancel() => IsSimulating;

    private bool CanSave() =>
    IsOutputReady
    && ObservableSolutions.Count > 0
    && HasErrors == false
    && string.IsNullOrWhiteSpace(BoardSizeText) == false;

    private async Task SimulateAsync()
    {
        Debug.WriteLine($"[SimulateAsync] Using solver instance: {_solver?.GetHashCode()}");
        if (_solver == null)
        {
            MessageBox.Show("Solver is not initialized.", "Error",
                MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }

        _solver.IsSolverCanceled = false;
        _currentSimulationToken = Guid.NewGuid();
        _solver.SetSimulationToken(_currentSimulationToken);

        try
        {
            if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
                return;

            Debug.WriteLine($"[SimulateAsync] Starting with BoardSize={boardSize}, Mode={SolutionMode}, Display={DisplayMode}");

            ResetSimulationState();
            ManageSimulationStatus(SimulationStatus.Started);
            UpdateUiState();

            var simContext = new SimulationContext(boardSize, SolutionMode, DisplayMode, EnableParallelization);
            _solver.DelayInMillisec = DelayInMilliseconds;

            SimulationResults = await _solver.GetSimResultsAsync(simContext);

            // Silent exit if canceled
            if (_solver.IsSolverCanceled || _currentSimulationToken == Guid.Empty)
                return;

            if (SimulationResults == null)
                throw new InvalidOperationException("No solutions were generated by the solver.");

            ExtractCorrectNoOfSols();
            NoOfSolutions = $"{SimulationResults.SolutionsCount,0:N0}";
            ElapsedTimeInSec = $"{SimulationResults.ElapsedTimeInSec,0:N1}";
            MemoryUsage = NumericUtils.UpdateMemoryUsage();

            if (ObservableSolutions.Count > 0)
                SelectedSolution = ObservableSolutions[0];

            IsOutputReady = ObservableSolutions.Count > 0;
        }
        catch (Exception ex)
        {
            if (_solver.IsSolverCanceled)
            {
                Debug.WriteLine($"[SimulateAsync] Suppressed exception after cancel: {ex.Message}");
            }
            else
            {
                Debug.WriteLine($"[SimulateAsync] Exception: {ex}");
                MessageBox.Show($"An error occurred during simulation: {ex.Message}", "Error",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
        finally
        {
            if (_solver.IsSolverCanceled)
            {
                // Ensure UI reflects canceled state
                IsSimulating = false;
                IsSingleRunning = false;
                ProgressVisibility = Visibility.Hidden;
                ProgressLabelVisibility = Visibility.Hidden;
                UnsubscribeFromSimulationEvents();
                RefreshCommandStates();
            }
            else
            {
                ManageSimulationStatus(SimulationStatus.Finished);
            }
        }
    }

    private void ManageSimulationStatus(SimulationStatus simulationStatus)
    {
        switch (simulationStatus)
        {
            case SimulationStatus.Started:
                SubscribeToSimulationEvents();
                IsIdle = false;
                IsInInputMode = false;
                IsSimulating = true;
                IsOutputReady = false;
                ProgressVisibility = Visibility.Visible;
                ProgressLabelVisibility = Visibility.Visible;
                ProgressValue = 0;
                ProgressLabel = "0%";
                IsSingleRunning = SolutionMode == SolutionMode.Single;
                break;

            case SimulationStatus.Finished:
                UnsubscribeFromSimulationEvents();
                IsIdle = true;
                IsInInputMode = true;
                IsSimulating = false;
                IsSingleRunning = false;
                IsOutputReady = true;
                ProgressVisibility = Visibility.Hidden;
                ProgressLabelVisibility = Visibility.Hidden;

                OnSimulationCompleted();

                // Fallback: fast simulations (small N) may have populated ObservableSolutions directly
                // (ExtractCorrectNoOfSols) without any batched events. Ensure first solution renders.
                if (SelectedSolution != null && ChessboardVm != null)
                {
                    EnsureBoardSized();
                    ChessboardVm.PlaceQueens(SelectedSolution.Positions);
                }
                break;
        }

        RefreshCommandStates();
    }

    private void ExtractCorrectNoOfSols()
    {
        ObservableSolutions.Clear();

        if (SimulationResults == null)
            return;

        // Decide how many to display. 0 or negative means "no cap".
        var cap = SimulationSettings.MaxNoOfSolutionsInOutput;
        IEnumerable<Solution> sols = SimulationResults.Solutions;

        if (cap > 0 && SimulationResults.SolutionsCount > cap)
            sols = sols.Take(cap);

        foreach (var s in sols)
            ObservableSolutions.Add(s);
    }

    private string GenerateSaveContent()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return string.Empty;

        StringBuilder sb = new();
        sb.AppendLine($"Date && Time: {DateTime.Now}");
        sb.AppendLine($"Board Size: {BoardSizeText}");
        sb.AppendLine($"SolutionMode: {SolutionMode}");
        sb.AppendLine($"Number of Solutions: {NoOfSolutions}");
        sb.AppendLine($"Max Number of Solutions Included: {SimulationSettings.MaxNoOfSolutionsInOutput}");
        sb.AppendLine($"Elapsed Time: {ElapsedTimeInSec} seconds");
        sb.AppendLine($"Memory Usage: {MemoryUsage} MB");
        sb.AppendLine();

        sb.AppendLine("Solutions:");
        foreach (var solution in ObservableSolutions)
        {
            sb.Append($"Solution ID: {solution.Id}\t\t\t");
            sb.AppendLine(solution.Details);
        }

        return sb.ToString();
    }

    private void UpdateUiState()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
            return;

        ObservableSolutions.Clear();
        NoOfSolutions = "0";
        ElapsedTimeInSec = $"{0,0:N1}";
        MemoryUsage = "0";
        ChessboardVm?.CreateSquares(boardSize);
    }

    private void RefreshCommandStates()
    {
        SimulateCommand?.NotifyCanExecuteChanged();
        CancelCommand?.NotifyCanExecuteChanged();
        SaveCommand?.NotifyCanExecuteChanged();
    }

    [RelayCommand]
    private void TestProgress()
    {
        ProgressValue += 0.1;
        if (ProgressValue > 1)
            ProgressValue = 0;
    }

    private Guid _currentSimulationToken = Guid.Empty;
}
