namespace NQueen.GUI.ViewModels;

public sealed partial class MainViewModel
{
    private void Cancel()
    {
        if (IsSimulating)
        {
            CancellationTokenSource?.Cancel();
            _solver.IsSolverCanceled = true;
            IsSimulating = false;
        }
    }

    private void Save()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return;

        var filePath = _saveFileService.ShowSaveFileDialog();
        if (string.IsNullOrEmpty(filePath))
            return;

        try
        {
            var content = GenerateSaveContent();
            _saveFileService.SaveContent(filePath, content);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[Save] Error during save operation: {ex.Message}");
            throw;
        }
    }

    private bool CanSimulate() => IsValid && HasErrors == false;

    private bool CanCancel() => IsSimulating;

    private bool CanSave() =>
    IsOutputReady
    && ObservableSolutions.Count > 0
    && HasErrors == false
    && string.IsNullOrWhiteSpace(BoardSizeText) == false;

    private async Task SimulateAsync()
    {
        Debug.WriteLine($"[SimulateAsync] Using solver instance: {_solver?.GetHashCode()}");
        if (_solver == null)
        {
            MessageBox.Show("Solver is not initialized.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            return;
        }

        _currentSimulationToken = Guid.NewGuid();
        _solver.SetSimulationToken(_currentSimulationToken);

        try
        {
            if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
                return;

            Debug.WriteLine($"[SimulateAsync] Starting with BoardSize={boardSize}, Mode={SolutionMode}, Display={DisplayMode}");

            ResetSimulationState();
            ManageSimulationStatus(SimulationStatus.Started);
            UpdateUiState();

            var simContext = new SimulationContext(boardSize, SolutionMode, DisplayMode);
            _solver.DelayInMillisec = DelayInMilliseconds;

            SimulationResults = await _solver.GetSimResultsAsync(simContext);

            if (SimulationResults == null || _currentSimulationToken == Guid.Empty)
                throw new InvalidOperationException("No solutions were generated by the solver.");

            ExtractCorrectNoOfSols();
            NoOfSolutions = $"{SimulationResults.SolutionsCount,0:N0}";
            ElapsedTimeInSec = $"{SimulationResults.ElapsedTimeInSec,0:N1}";
            SelectedSolution = ObservableSolutions.FirstOrDefault()
                ?? new Solution([], null!);
            MemoryUsage = NumericUtils.UpdateMemoryUsage();
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[SimulateAsync] Exception: {ex}");
            MessageBox.Show($"An error occurred during simulation: {ex.Message}", "Error",
                MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            ManageSimulationStatus(SimulationStatus.Finished);
        }
    }

    private void ManageSimulationStatus(SimulationStatus simulationStatus)
    {
        switch (simulationStatus)
        {
            case SimulationStatus.Started:
                SubscribeToSimulationEvents();
                IsIdle = false;
                IsInInputMode = false;
                IsSimulating = true;
                IsOutputReady = false;

                ProgressVisibility = Visibility.Visible;
                ProgressLabelVisibility = Visibility.Visible;
                ProgressValue = 0;
                IsSingleRunning = SolutionMode == SolutionMode.Single;
                break;

            case SimulationStatus.Finished:
                UnsubscribeFromSimulationEvents();
                IsIdle = true;
                IsInInputMode = true;
                IsSimulating = false;
                IsSingleRunning = false;
                IsOutputReady = true;
                ProgressVisibility = Visibility.Hidden;
                ProgressLabelVisibility = Visibility.Hidden;
                OnSimulationCompleted();
                break;
        }

        RefreshCommandStates();
    }

    private void ExtractCorrectNoOfSols()
    {
        ObservableSolutions.Clear();

        if (SimulationResults == null)
            return;

        // Decide how many to display. 0 or negative means "no cap".
        var cap = SimulationSettings.MaxNoOfSolutionsInOutput;
        IEnumerable<Solution> sols = SimulationResults.Solutions;

        if (cap > 0 && SimulationResults.SolutionsCount > cap)
            sols = sols.Take(cap);

        foreach (var s in sols)
            ObservableSolutions.Add(s);
    }

    private string GenerateSaveContent()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return string.Empty;

        StringBuilder sb = new();
        sb.AppendLine($"Date && Time: {DateTime.Now}");
        sb.AppendLine($"Board Size: {BoardSizeText}");
        sb.AppendLine($"SolutionMode: {SolutionMode}");
        sb.AppendLine($"Number of Solutions: {NoOfSolutions}");
        sb.AppendLine($"Max Number of Solutions Included: {SimulationSettings.MaxNoOfSolutionsInOutput}");
        sb.AppendLine($"Elapsed Time: {ElapsedTimeInSec} seconds");
        sb.AppendLine($"Memory Usage: {MemoryUsage} MB");
        sb.AppendLine();

        sb.AppendLine("Solutions:");
        foreach (var solution in ObservableSolutions)
        {
            sb.Append($"Solution ID: {solution.Id}\t\t\t");
            sb.AppendLine(solution.Details);
        }

        return sb.ToString();
    }

    private void UpdateUiState()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
            return;

        ObservableSolutions.Clear();
        NoOfSolutions = "0";
        ElapsedTimeInSec = $"{0,0:N1}";
        MemoryUsage = "0";
        ChessboardVm?.CreateSquares(boardSize);
    }

    private void RefreshCommandStates()
    {
        SimulateCommand?.NotifyCanExecuteChanged();
        CancelCommand?.NotifyCanExecuteChanged();
        SaveCommand?.NotifyCanExecuteChanged();
    }

    [RelayCommand]
    private void TestProgress()
    {
        ProgressValue += 0.1;
        if (ProgressValue > 1)
            ProgressValue = 0;
    }

    private Guid _currentSimulationToken = Guid.Empty;
}
