namespace NQueen.GUI.ViewModels;

public sealed partial class MainViewModel
{
    private void Cancel()
    {
        if (IsSimulating)
        {
            CancellationTokenSource?.Cancel();
            _solver.IsSolverCanceled = true;
            IsSimulating = false;
        }
    }

    private void Save()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return;

        var filePath = _saveFileService.ShowSaveFileDialog();
        if (string.IsNullOrEmpty(filePath))
            return;

        try
        {
            var content = GenerateSaveContent();
            _saveFileService.SaveContent(filePath, content);
        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[Save] Error during save operation: {ex.Message}");
            throw;
        }
    }

    private bool CanSimulate() => IsValid && HasErrors == false;

    private bool CanCancel() => IsSimulating;

    private bool CanSave() => IsOutputReady;

    private async Task SimulateAsync()
    {
        // Generate a new token for this simulation run
        _currentSimulationToken = Guid.NewGuid();

        // Synchronize the token with the orchestrator
        if (_solver is SimulationOrchestrator orchestrator)
        {
            orchestrator.SetSimulationToken(_currentSimulationToken);
        }

        try
        {
            if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
                return;

            ManageSimulationStatus(SimulationStatus.Started);
            UpdateUiState();
            SimulationResults = await _solver.GetResultsForBoardAsync(boardSize, SolutionMode, DisplayMode);

            // After awaiting, check if this is still the current simulation
            if (SimulationResults == null || !SimulationResults.Solutions.Any() || _currentSimulationToken == Guid.Empty)
                throw new InvalidOperationException("No solutions were generated by the solver.");

            ExtractCorrectNoOfSols();
            NoOfSolutions = $"{SimulationResults.NoOfSolutions,0:N0}";
            ElapsedTimeInSec = $"{SimulationResults.ElapsedTimeInSec,0:N1}";
            SelectedSolution = ObservableSolutions.FirstOrDefault() ?? new Solution([], null);
            MemoryUsage = NumericUtility.UpdateMemoryUsage();

        }
        catch (Exception ex)
        {
            Debug.WriteLine($"[SimulateAsync] Error: {ex.Message}");
            MessageBox.Show($"An error occurred during simulation: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            ManageSimulationStatus(SimulationStatus.Finished);
        }
    }

    private void ManageSimulationStatus(SimulationStatus simulationStatus)
    {
        switch (simulationStatus)
        {
            case SimulationStatus.Started:
                SubscribeToSimulationEvents();
                IsIdle = false;
                IsInInputMode = false;
                IsSimulating = true;
                IsOutputReady = false;

                ProgressVisibility = Visibility.Visible;
                ProgressLabelVisibility = Visibility.Visible;
                ProgressValue = 0;
                IsSingleRunning = SolutionMode == SolutionMode.Single;
                break;

            case SimulationStatus.Finished:
                UnsubscribeFromSimulationEvents();
                IsIdle = true;
                IsInInputMode = true;
                IsSimulating = false;
                IsSingleRunning = false;
                IsOutputReady = true;
                ProgressVisibility = Visibility.Hidden;
                ProgressLabelVisibility = Visibility.Hidden;
                OnSimulationCompleted();
                break;
        }

        RefreshCommandStates();
    }

    private void ExtractCorrectNoOfSols()
    {
        ObservableSolutions.Clear();
        var sols = SimulationResults.Solutions.Take(SimulationSettings.MaxNoOfSolutionsInOutput);
        foreach (var s in sols)
            ObservableSolutions.Add(s);
    }

    private string GenerateSaveContent()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var _) == false)
            return string.Empty;

        StringBuilder sb = new();
        sb.AppendLine($"Date && Time: {DateTime.Now}");
        sb.AppendLine($"Board Size: {BoardSizeText}");
        sb.AppendLine($"SolutionMode: {SolutionMode}");
        sb.AppendLine($"Number of Solutions: {NoOfSolutions}");
        sb.AppendLine($"Max Number of Solutions Included: {SimulationSettings.MaxNoOfSolutionsInOutput}");
        sb.AppendLine($"Elapsed Time: {ElapsedTimeInSec} seconds");
        sb.AppendLine($"Memory Usage: {MemoryUsage} MB");
        sb.AppendLine();

        sb.AppendLine("Solutions:");
        foreach (var solution in ObservableSolutions)
        {
            sb.Append($"Solution ID: {solution.Id}\t\t\t");
            sb.AppendLine(solution.Details);
        }

        return sb.ToString();
    }

    private void UpdateUiState()
    {
        if (ParsingUtils.TryParseInt(BoardSizeText, out var boardSize) == false)
            return;

        ObservableSolutions.Clear();
        NoOfSolutions = "0";
        ElapsedTimeInSec = $"{0,0:N1}";
        MemoryUsage = "0";
        ChessboardVm?.CreateSquares(boardSize);
    }

    private void RefreshCommandStates()
    {
        SimulateCommand?.NotifyCanExecuteChanged();
        CancelCommand?.NotifyCanExecuteChanged();
        SaveCommand?.NotifyCanExecuteChanged();
    }

    [RelayCommand]
    private void TestProgress()
    {
        ProgressValue += 0.1;
        if (ProgressValue > 1)
            ProgressValue = 0;
    }


    private Guid _currentSimulationToken = Guid.Empty;
}
