global using FluentAssertions;
global using NQueen.Kernel;
global using NQueen.Shared;
global using NQueen.Shared.Enums;
global using NQueen.Shared.Interfaces;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Xunit;
